id: IC973770A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T15:24:23+00:00'
last_modified: '2022-06-08T01:15:28.668431+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W28962
  title: ཆེད་རྩོམ། ཆབ་འགག་རྟ་མགྲིན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    8C8E:
      image_group_id: I1GS66313
      title: ''
      total_pages: 474
      order: 1
      base_file: 8C8E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
