id: P004462
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W28962
  title: ཆེད་རྩོམ། ཆབ་འགག་རྟ་མགྲིན
  author: ''
  volumes:
    8ee05bcbaa6b4b3e88ee6f0437f009d5:
      image_group_id: I1GS66313
      title: ''
      volume_number: 1
      total_pages: 474
      base_file: v001.txt
